##
## Username
##
username:
    type: text
    help: 'Specify the Username that will be used to enter the Network'
    title: "Set this User's Username"
    name: account_username
    label: 'Username'
    class: big-text
    id: account-username

##
## Fullname
##
fullname:
    type: text
    help: "Set this User's full name for identification"
    title: "Set this User's Full Name"
    name: account_fullname
    label: 'Full Name'
    class: big-text
    id: account-fullname

##
## User Description
##  
description:
    type: text
    help: 'Set a description for this User if there is anything special about him'
    title: 'Set a Description for this User'
    name: account_description
    label: 'Description'
    class: big-text
    id: account-description

##
## Password
##
password:
    type: text
    help: "Change this User's Password. If this is a new user you must specify a new password. If you are editing a user you can leave this field empty to leave the password unchanged"
    title: "Set this User's Password"
    name: account_password
    label: 'Password'
    class: big-text
    id: account-password

##
## Confirm Password
##
confirmpassword:
    type: text
    help: 'Confirm the new Password you set above'
    title: 'Confirm the Password'
    name: confirm_password
    label: 'Confirm Password'
    class: big-text
    id: account-confirm-password
    
##
## Must Change Password at Next Logon
##
mustchange:
    type: checkbox
    help: 'Forces this User to change his password the next time he logs into the System'
    title: 'Check to force a Password Change at the next Logon'
    name: account_must_change_password
    label: 'Force Password Change at Next Logon'
    class: big-margin
    id: account-must-change

##
## Cannot Change Password
##
cannotchange:
    type: checkbox
    help: 'Specifies that this User cannot change his Password'
    title: 'Check to deny this User a Password Change'
    name: account_cannot_change_password
    label: 'Cannot Change Password'
    class: big-margin
    id: account-cannot-change

##
## Password Never Expires
##
neverexpires:
    type: checkbox
    help: 'When checked this means that this User will not be affected by Password Chaging policies'
    title: "Check to make sure that this User's Password will not expire"
    name: account_password_never_expires
    label: 'Password Never Expires'
    class: big-margin
    id: account-never-expires

##
## Account Disabled
##
disabled:
    type: checkbox
    help: 'When checked this means that this Account will be disabled and the User will not the able to logon'
    title: "Check to disable this Account"
    name: account_account_disabled
    label: 'Account Disabled'
    class: big-margin
    id: account-disabled

##
## Account Locked
##
locked:
    type: checkbox
    help: 'Account Locked'
    title: "Check to lock this Account"
    name: account_account_locked_out
    label: 'Account Locked'
    class: big-margin
    id: account-locked
    
##
## Profile Path
## 
profilepath:
    type: text
    help: 'Profile Path'
    title: 'Profile Path'
    name: account_profile_path
    label: 'User Profile Path'
    class: big-text
    id: account-profile-path

    field-ops:
        - path-selection

    field-ops-descriptor:
        path-selection:
            title: 'Select the Profile Path for this User'
            image:
                name: layer-select-point.png
                alt: 'Select Path Icon'
            link:
                controller: share
                action: path

##
## Logon Script Name
##
logonscriptname:
    type: text
    help: 'Specify the Username that will be used to enter the Network'
    title: "Set this User's Username"
    name: account_logon_script
    label: 'Logon Script Name'
    class: big-text
    id: account-logon-script-name

##
## Home Directory Path
##
homedirpath:
    type: text
    help: 'Home Directory Path'
    title: 'Home Directory Path'
    name: account_homedir_path
    label: 'Home Directory Path'
    class: big-text
    id: account-homedir-path

    field-ops:
        - path-selection

    field-ops-descriptor:
        path-selection:
            title: 'Select the Home Directory Path for this User'
            image:
                name: layer-select-point.png
                alt: 'Select Path Icon'
            link:
                controller: share
                action: path

##
## Home Directory Path
##
maphomedirdrive:
    type: text
    help: 'Map Home Directory to Drive'
    title: 'Map Home Directory to Drive'
    name: account_map_homedir_drive
    label: 'Map Home to Drive'
    class: big-text
    id: account-homedir-path
    
##
## Home Directory Path
##
groups:
    type: list
    help: 'List of Groups that this User belongs to'
    title: 'Select the Groups that this User will be a part of'
    name: account_group_list
    label: 'Groups'
    class: big-text
    id: account-insert-groups
    
    field-ops:
        - manual-add
        - user-group-selection

    field-ops-descriptor:
        user-group-selection:
            title: 'Open Group Selection Popup'
            image:
                name: users.png
                alt: 'Select Users/Groups Icon'
            link:
                controller: account
                action: show_groups
                copy-to: account-insert-groups-list
                
        manual-add:
            title: 'Assign this Group. Separate by , to add more than one'
            image:
                name: plus-small.png
                alt: 'Add User/Group Icon'
            link:
                copy-from: account-insert-groups
                copy-to: account-insert-groups-list
